#

mssql: &mssql
  adapter: sqlserver
  encoding: utf8
  username: sa
  password: Pas_w0rd
  host: localhost

mysql: &mysql
  adapter: mysql2
  encoding: utf8mb4
  username: root
  socket: /tmp/mysql.sock
  host: /tmp

# oracle: &oracle
#   adapter: oracle_enhanced
#   username: useroracle
#   password: passwordoracle
#   database: "(DESCRIPTION=
#     (ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=localhost)(PORT=1521)))
#     (CONNECT_DATA=(SERVICE_NAME=xe))
#   )"

# sqlplus system/Pas_w0rd@localhost/XE
# usql oracle://system:Pas_w0rd@localhost/xe
oracle18c: &oracle18c
  adapter: oracle_enhanced
  username: useroracle
  password: passwordoracle
  database: //localhost/XE

pgsql: &pgsql
  adapter: postgresql
  encoding: unicode
  username: postgres

default: &default
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') %>
  database: blog_development
  <<: *oracle18c

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

